/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package FramesAdministrador;

import BancoDeDados.ConectaBD;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author  Raphael e Leonardo
 */
public class Consulta extends javax.swing.JFrame {
    ConectaBD conecta= new ConectaBD();//instancia da classe de conexão

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
        conecta.conexao();//Chamada do metodo de conexão
        preencherTabelaTurmasDisp("select * from Turmas order by Cod_turma");//Chamada que Preenche a Tabela de Disciplinas/turmas
        preencherTabelaCurso("select * from Curso order by Cod_Curso");//Chamada que Preenche a Tabela de Cursos
        preencherTabDiscCurso("select *\n" +
                              "from disciplinas d, turmas t, professores p\n" +
                              "where d.Cod_disc=T.Cod_disc and p.Mat_Siape=t.Mat_Siape;");//Chamada que Preenche a Tabela de Discentes por Cursos
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabTurmasDisp = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabAlunosNaTurma1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabcursosDisp = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TabprofsNosCursos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TabDiscCurso = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setViewportView(TabTurmasDisp);

        TabAlunosNaTurma1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TabAlunosNaTurma1);

        jLabel1.setText("Turmas Cadastradas:");

        jLabel2.setText("Resultado da Consulta em ordem alfabética:");

        jLabel3.setText("Digite o Código da Turma:");

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CONSULTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("CONSULTAR ALUNOS POR TURMA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton1))
                    .addComponent(jLabel4))
                .addGap(97, 97, 97))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel2)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Alunos por Turma", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("CONSULTAR PROFESSORES POR CURSO");

        jLabel6.setText("Cursos Cadastrados:");

        jScrollPane3.setViewportView(TabcursosDisp);

        jLabel7.setText("Digite o Código do Curso:");

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CONSULTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Resultado da Consulta em ordem alfabética:");

        TabprofsNosCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(TabprofsNosCursos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(242, 242, 242)
                            .addComponent(jLabel6))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(187, 187, 187)
                            .addComponent(jLabel8))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(115, 115, 115)
                            .addComponent(jLabel5))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Professores por Curso", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("CONSULTAR DISCIPLINAS/TURMAS");

        jLabel10.setText("Disciplinas e suas respectivas turmas:");

        TabDiscCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(TabDiscCurso);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel10)))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Disciplinas/Turmas", jPanel3);

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SAIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("VOLTAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 0));
        jLabel11.setText("AMBIENTE DE CONSULTAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(59, 59, 59)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       preencherTabAlunosNaTurma("select * from turmas t, disciplinas d, participa_de pd, alunos a \n" +
            "where t.Cod_disc=d.Cod_disc and pd.Cod_Turma=t.Cod_Turma and pd.Cod_disc=d.Cod_disc and\n" +
            "a.matricula=pd.matricula and\n" +
            "t.Cod_turma='"+jTextField1.getText()+"' ORDER BY a.Nome;");//Chamada que Preenche a Tabela de Alunos na Turma quando o botão é acionado
    }//GEN-LAST:event_jButton1ActionPerformed
 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        preencherTabProfsNoCurso("select * from curso c, professores p where p.Cod_Curso=c.Cod_Curso and c.Cod_Curso= '"+jTextField2.getText()+"' order by p.Nome ;");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        OpAdmr fr = new OpAdmr();
            fr.setLocationRelativeTo(null);
            fr.setDefaultCloseOperation(fr.DISPOSE_ON_CLOSE);
            fr.setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
public void preencherTabelaTurmasDisp(String SQL){//Preenche a Tabela de Turmas na Disciplina
     ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"Cod_turma","Num_alunos","Local","Horário","Semestre","Mat_Siape","Cod_disc"};
    
    conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
             do{ 
                 dados.add(new Object[]{conecta.rs.getInt("Cod_turma"), conecta.rs.getString("Num_alunos"),conecta.rs.getString("Local"),conecta.rs.getTime("Horário"),conecta.rs.getString("Semestre"),conecta.rs.getInt("Mat_Siape"),conecta.rs.getInt("Cod_disc") });
    }while(conecta.rs.next());
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"Erro ao preencher a tabela \n erro:"+ex);
        }

    ModeloTabela modelo = new ModeloTabela(dados, Colunas);
    TabTurmasDisp.setModel(modelo);
    TabTurmasDisp.getColumnModel().getColumn(0).setPreferredWidth(80);//indice 0 Cursos
    TabTurmasDisp.getColumnModel().getColumn(0).setResizable(false);//nao pode alterar o tamanho com o mouse
    TabTurmasDisp.getColumnModel().getColumn(1).setPreferredWidth(80);//indice 1 Cursos
    TabTurmasDisp.getColumnModel().getColumn(1).setResizable(false);//nao pode alterar o tamanho com o mouse
    TabTurmasDisp.getColumnModel().getColumn(2).setPreferredWidth(80);//indice 1 Cursos
    TabTurmasDisp.getColumnModel().getColumn(2).setResizable(false);//nao pode alterar o tamanho com o mouse
    TabTurmasDisp.getColumnModel().getColumn(3).setPreferredWidth(90);//indice 0 Cursos
    TabTurmasDisp.getColumnModel().getColumn(3).setResizable(false);//nao pode alterar o tamanho com o mouse
    TabTurmasDisp.getColumnModel().getColumn(4).setPreferredWidth(80);//indice 0 Cursos
    TabTurmasDisp.getColumnModel().getColumn(4).setResizable(false);//nao pode alterar o tamanho com o mouse
    TabTurmasDisp.getColumnModel().getColumn(5).setPreferredWidth(80);//indice 0 Cursos
    TabTurmasDisp.getColumnModel().getColumn(5).setResizable(false);//nao pode alterar o tamanho com o mouse
    TabTurmasDisp.getColumnModel().getColumn(6).setPreferredWidth(80);//indice 0 Cursos
    TabTurmasDisp.getColumnModel().getColumn(6).setResizable(false);//nao pode alterar o tamanho com o mouse
    TabTurmasDisp.getTableHeader().setReorderingAllowed(false);//reorganizar a alocaçao
    TabTurmasDisp.setAutoResizeMode(TabTurmasDisp.AUTO_RESIZE_OFF);//nao podera ser redimensionada;
    TabTurmasDisp.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
}
public void preencherTabAlunosNaTurma(String SQL){
      
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"Matr. Aluno","Nome Aluno"};
    
    conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
             do{ 
                 dados.add(new Object[]{conecta.rs.getInt("a.Matricula"),conecta.rs.getString("a.Nome")});
    }while(conecta.rs.next());
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"A turma não possui ALUNOS!");
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        TabAlunosNaTurma1.setModel(modelo);
        TabAlunosNaTurma1.getColumnModel().getColumn(0).setPreferredWidth(70);//indice 0 Cursos
        TabAlunosNaTurma1.getColumnModel().getColumn(0).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabAlunosNaTurma1.getColumnModel().getColumn(1).setPreferredWidth(200);//indice 0 Cursos
        TabAlunosNaTurma1.getColumnModel().getColumn(1).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabAlunosNaTurma1.getTableHeader().setReorderingAllowed(false);//reorganizar a alocaçao
        TabAlunosNaTurma1.setAutoResizeMode(TabAlunosNaTurma1.AUTO_RESIZE_OFF);//nao podera ser redimensionada;
        TabAlunosNaTurma1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
}
        public void preencherTabelaCurso(String SQL){
            ArrayList dados = new ArrayList();
            String [] Colunas = new String[]{"Cod_Curso","Nome_Curso"};

            conecta.executaSQL(SQL);
                try {
                    conecta.rs.first();
                     do{ 
                         dados.add(new Object[]{conecta.rs.getInt("Cod_Curso"), conecta.rs.getString("Nome_Curso")});
            }while(conecta.rs.next());
                } catch (SQLException ex) {
                     JOptionPane.showMessageDialog(rootPane,"Erro ao preencher a tabela");
                }

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        TabcursosDisp.setModel(modelo);
        TabcursosDisp.getColumnModel().getColumn(0).setPreferredWidth(80);//indice 0 Cursos
        TabcursosDisp.getColumnModel().getColumn(0).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabcursosDisp.getColumnModel().getColumn(1).setPreferredWidth(180);//indice 1 Cursos
        TabcursosDisp.getColumnModel().getColumn(1).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabcursosDisp.getTableHeader().setReorderingAllowed(false);//reorganizar a alocaçao
        TabcursosDisp.setAutoResizeMode(TabcursosDisp.AUTO_RESIZE_OFF);//naopodera ser redimensionada;
        TabcursosDisp.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
}
 public void preencherTabProfsNoCurso(String SQL){
      
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"Mat Siape","Nome do Professor"};
    
    conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
             do{ 
                 dados.add(new Object[]{conecta.rs.getInt("p.Mat_Siape"),conecta.rs.getString("p.Nome")});
    }while(conecta.rs.next());
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"O CURSO não possui PROFESSORES Cadastrados!");
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        TabprofsNosCursos.setModel(modelo);
        TabprofsNosCursos.getColumnModel().getColumn(0).setPreferredWidth(70);//indice 0 Cursos
        TabprofsNosCursos.getColumnModel().getColumn(0).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabprofsNosCursos.getColumnModel().getColumn(1).setPreferredWidth(200);//indice 0 Cursos
        TabprofsNosCursos.getColumnModel().getColumn(1).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabprofsNosCursos.getTableHeader().setReorderingAllowed(false);//reorganizar a alocaçao
        TabprofsNosCursos.setAutoResizeMode(TabprofsNosCursos.AUTO_RESIZE_OFF);//nao podera ser redimensionada;
        TabprofsNosCursos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
}
public void preencherTabDiscCurso(String SQL){
      
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"Nome Disciplina","Cod da Turma","Local","Horário","Professor"};
    
    conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
             do{ 
                 dados.add(new Object[]{conecta.rs.getString("d.Nome"),conecta.rs.getInt("t.Cod_turma"),conecta.rs.getString("t.Local"),conecta.rs.getTime("t.Horário"),conecta.rs.getString("p.Nome")});
    }while(conecta.rs.next());
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"Erro ao mostrar Dados!"+ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        TabDiscCurso.setModel(modelo);
        TabDiscCurso.getColumnModel().getColumn(0).setPreferredWidth(200);//indice 0 Cursos
        TabDiscCurso.getColumnModel().getColumn(0).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDiscCurso.getColumnModel().getColumn(1).setPreferredWidth(90);//indice 0 Cursos
        TabDiscCurso.getColumnModel().getColumn(1).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDiscCurso.getColumnModel().getColumn(2).setPreferredWidth(90);//indice 0 Cursos
        TabDiscCurso.getColumnModel().getColumn(2).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDiscCurso.getColumnModel().getColumn(3).setPreferredWidth(70);//indice 0 Cursos
        TabDiscCurso.getColumnModel().getColumn(3).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDiscCurso.getColumnModel().getColumn(4).setPreferredWidth(150);//indice 0 Cursos
        TabDiscCurso.getColumnModel().getColumn(4).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDiscCurso.getTableHeader().setReorderingAllowed(false);//reorganizar a alocaçao
        TabDiscCurso.setAutoResizeMode(TabDiscCurso.AUTO_RESIZE_OFF);//nao podera ser redimensionada;
        TabDiscCurso.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabAlunosNaTurma1;
    private javax.swing.JTable TabDiscCurso;
    private javax.swing.JTable TabTurmasDisp;
    private javax.swing.JTable TabcursosDisp;
    private javax.swing.JTable TabprofsNosCursos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
