/*
 Tela de Ambiente do Aluno
 */

package FramesAluno;

import BancoDeDados.ConectaBD;
import FramesAdministrador.ModeloTabela;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author  Raphael e Leonardo
 */
public class AlunoEntrar extends javax.swing.JFrame {

   ConectaBD conecta= new ConectaBD();//instancia da classe de conexão
   ConectaBD conCurso= new ConectaBD();//INSTANCIA PARA USAR O COMBO BOX
    /**
     * Creates new form Cadastro
     */
   
       
    public AlunoEntrar() {
        initComponents();
        conecta.conexao();//Chamada do metodo de conexão
     
       
    }
    public void recebendo(String recebe){//Responsável por enviar a Matricula do Aluno
      jLabel17.setText(recebe);
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabDisciplinasAluno = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton34 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabDisciplinasRestantes = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        campo_codTurma = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        campo_CodDisc = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabNotas = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("MATRÍCULA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));

        jLabel3.setText("NOME:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));

        jLabel5.setText("ENDEREÇO: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));

        jLabel7.setText("TELEFONES: ");

        jLabel9.setText("CURSO:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Bem Vindo(a)!");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(328, 328, 328))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 168, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados do Aluno", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Turmas");

        TabDisciplinasAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TabDisciplinasAluno);

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Realizar Matrícula");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Trancar Turma");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Você está matriculado nas Turmas:");

        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3.png"))); // NOI18N
        jButton34.setToolTipText("Primeiro Registro");
        jButton34.setName(""); // NOI18N
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.png"))); // NOI18N
        jButton36.setToolTipText("Registro Anterior");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1.png"))); // NOI18N
        jButton37.setToolTipText("Próximo Registro");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4.png"))); // NOI18N
        jButton35.setToolTipText("Ultimo Registro");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        TabDisciplinasRestantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TabDisciplinasRestantes);

        jLabel22.setText("Turmas disponíveis:");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));

        campo_codTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_codTurmaActionPerformed(evt);
            }
        });

        campo_CodDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_CodDiscActionPerformed(evt);
            }
        });

        jLabel23.setText("Codigo Turma:");

        jLabel24.setText("Código Disciplina:");

        jLabel25.setText("Nome da Disciplina:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3.png"))); // NOI18N
        jButton38.setToolTipText("Primeiro Registro");
        jButton38.setName(""); // NOI18N
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4.png"))); // NOI18N
        jButton39.setToolTipText("Ultimo Registro");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });

        jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1.png"))); // NOI18N
        jButton40.setToolTipText("Próximo Registro");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });

        jButton41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.png"))); // NOI18N
        jButton41.setToolTipText("Registro Anterior");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        jLabel26.setText("Nome do Professor:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel27.setText("Carga Horária (CH):");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(jLabel19)
                                .addGap(333, 333, 333)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_codTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_CodDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(293, 293, 293)
                                .addComponent(jLabel22)))
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(229, 229, 229)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(19, 19, 19))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(366, 366, 366))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(5, 5, 5)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton37, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jButton2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo_codTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo_CodDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton40, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Turmas", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setText("Suas notas são");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setText("Notas");

        tabNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabNotas);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("IRA:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Notas", jPanel3);

        jLabel16.setText("Sua Matrícula:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jLabel17HierarchyChanged(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CONFIRMAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("VOLTAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SAIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel16)
                .addGap(27, 27, 27)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addComponent(jButton3))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel17HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17HierarchyChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Ao clicar nesse botão todas as informações do aluno aparecem
        preencherTabDiscAlunos("select * from Turmas t, Disciplinas d, participa_de p, alunos a, professores r where r.Mat_Siape = t.Mat_Siape and p.Cod_disc=d.Cod_disc and t.Cod_disc=p.Cod_disc and a.Matricula=p.Matricula and a.Matricula='"+  jLabel17.getText() +"' order by t.Cod_turma ;");
        preencherTabNotas("select d.Nome as Nome_disciplina, Notas as Notas from alunos a, participa_de p, disciplinas d where a.Matricula=p.Matricula and p.Cod_disc=d.Cod_disc and a.Matricula= '"+  jLabel17.getText() +"' ;");
        preencherTabDiscRestantes("select * from  disciplinas d,professores p,Turmas t where p.Mat_Siape = t.Mat_Siape and t.Cod_disc=d.Cod_disc");
         //Preenchimento do Combo Box - Telefones
        conCurso.conexao();
        conCurso.executaSQL("select * from telefones where Alunos_Matricula='"+jLabel17.getText()+"' order by Numero_Tel");
        jComboBox1.removeAllItems();
        try{
            conCurso.rs.first();
                do{
                    jComboBox1.addItem(conCurso.rs.getString("Numero_Tel"));  
                }while(conCurso.rs.next());             
                }catch(SQLException ex){                   
                }  
        //Mostra os dados do aluno na tela incial
        try {
            conecta.executaSQL("Select * from alunos a, curso c where a.Cod_Curso=c.Cod_Curso and Matricula="+jLabel17.getText());
            conecta.rs.first();
           jLabel2.setText(String.valueOf(conecta.rs.getInt("a.Matricula")));
           jLabel4.setText(conecta.rs.getString("a.Nome"));
           jLabel6.setText(conecta.rs.getString("a.Endereço"));
           jLabel10.setText(conecta.rs.getString("c.Nome_Curso")); 
        }catch(SQLException ex){   
            JOptionPane.showMessageDialog(null,"Erro ao mostrar dados!\nERRO:"+ex);  
        }  
        try {//calcular IRA
            conecta.executaSQL("select AVG( Notas )as media_Aluno from alunos a, participa_de p, disciplinas d where a.Matricula=p.Matricula and p.Cod_disc=d.Cod_disc and a.Matricula= '"+jLabel17.getText()+"'");
            conecta.rs.first();
           jLabel13.setText(String.valueOf(conecta.rs.getFloat("media_Aluno")));
           try{//Insere IRA no Banco de dados
            PreparedStatement pst = conecta.conn.prepareStatement(" UPDATE Alunos SET IRA= ? WHERE Matricula = ? ;");//passagem do SQL para inserção
            pst.setString(1,jLabel13.getText());//passagem de parametros
            pst.setString(2,jLabel17.getText());
            pst.executeUpdate();//executa a alteração
           // JOptionPane.showMessageDialog(rootPane,"Salvo com Sucesso!");
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Erro ao Salvar IRA! \n ERRO: "+ex);
        }
        }catch(SQLException ex){   
            JOptionPane.showMessageDialog(null,"Erro ao mostrar dados!\nERRO:"+ex);  
        }  
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void campo_CodDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_CodDiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_CodDiscActionPerformed

    private void campo_codTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_codTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_codTurmaActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        try {
            conecta.executaSQL("select * from Turmas t, Disciplinas d, participa_de p, alunos a, professores r where r.Mat_Siape = t.Mat_Siape and p.Cod_disc=d.Cod_disc and t.Cod_disc=p.Cod_disc and a.Matricula=p.Matricula and a.Matricula='"+  jLabel17.getText() +"' order by t.Cod_turma ;");
            conecta.rs.last();
            campo_codTurma.setText(String.valueOf(conecta.rs.getInt("t.Cod_turma")));
            campo_CodDisc.setText(String.valueOf(conecta.rs.getInt("d.Cod_disc")));;
            jTextField3.setText(conecta.rs.getString("d.Nome"));
            jTextField5.setText(conecta.rs.getString("d.Carga_horária"));
            jTextField4.setText(conecta.rs.getString("r.Nome"));
        }catch(SQLException ex){
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        try {
            conecta.rs.next();
            campo_codTurma.setText(String.valueOf(conecta.rs.getInt("t.Cod_turma")));
            campo_CodDisc.setText(String.valueOf(conecta.rs.getInt("d.Cod_disc")));;
            jTextField3.setText(conecta.rs.getString("d.Nome"));
            jTextField5.setText(conecta.rs.getString("d.Carga_horária"));
            jTextField4.setText(conecta.rs.getString("r.Nome"));
        }catch(SQLException ex){
           Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        try {
            conecta.rs.previous();
            campo_codTurma.setText(String.valueOf(conecta.rs.getInt("t.Cod_turma")));
            campo_CodDisc.setText(String.valueOf(conecta.rs.getInt("d.Cod_disc")));;
            jTextField3.setText(conecta.rs.getString("d.Nome"));
            jTextField5.setText(conecta.rs.getString("d.Carga_horária"));
            jTextField4.setText(conecta.rs.getString("r.Nome"));
        }catch(SQLException ex){
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed

        try {
            conecta.executaSQL("select * from Turmas t, Disciplinas d, participa_de p, alunos a, professores r where r.Mat_Siape = t.Mat_Siape and p.Cod_disc=d.Cod_disc and t.Cod_disc=p.Cod_disc and a.Matricula=p.Matricula and a.Matricula='"+  jLabel17.getText() +"' order by t.Cod_turma ;");
            conecta.rs.first();
            campo_codTurma.setText(String.valueOf(conecta.rs.getInt("t.Cod_turma")));
            campo_CodDisc.setText(String.valueOf(conecta.rs.getInt("d.Cod_disc")));;
            jTextField3.setText(conecta.rs.getString("d.Nome"));
            jTextField5.setText(conecta.rs.getString("d.Carga_horária"));
            jTextField4.setText(conecta.rs.getString("r.Nome"));       
        }catch(SQLException ex){
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
            PreparedStatement pst=conecta.conn.prepareStatement("DELETE  FROM Participa_de WHERE Cod_turma = ? ;");
            pst.setString(1,campo_codTurma.getText());
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Excluido com Sucesso!");
        }catch(SQLException  ex){
             JOptionPane.showMessageDialog(rootPane,"Erro ao Excluirr! \nERRO:"+ex);
            
        }
        preencherTabDiscAlunos("select * from Turmas t, Disciplinas d, participa_de p, alunos a, professores r where r.Mat_Siape = t.Mat_Siape and p.Cod_disc=d.Cod_disc and t.Cod_disc=p.Cod_disc and a.Matricula=p.Matricula and a.Matricula='"+  jLabel17.getText() +"' order by t.Cod_turma ;");
        preencherTabNotas("select d.Nome as Nome_disciplina, Notas as Notas from alunos a, participa_de p, disciplinas d where a.Matricula=p.Matricula and p.Cod_disc=d.Cod_disc and a.Matricula= '"+  jLabel17.getText() +"' ;");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{//BOTÃO DE INSERÇÃO
        PreparedStatement pst = conecta.conn.prepareStatement("INSERT INTO Participa_de (Matricula,Cod_turma,Cod_disc) VALUES (?,?,?)");//passagem do SQL para inserção
        pst.setString(1,jLabel17.getText());//matricula
        pst.setString(2,campo_codTurma.getText());
        pst.setString(3,campo_CodDisc.getText());
        pst.executeUpdate();//executa a inserção
        JOptionPane.showMessageDialog(rootPane,"Salvo com Sucesso!");
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Erro ao Salvar! \n ERRO: "+ex);
        }
      preencherTabDiscAlunos("select * from Turmas t, Disciplinas d, participa_de p, alunos a, professores r where r.Mat_Siape = t.Mat_Siape and p.Cod_disc=d.Cod_disc and t.Cod_disc=p.Cod_disc and a.Matricula=p.Matricula and a.Matricula='"+  jLabel17.getText() +"' order by t.Cod_turma ;");
      preencherTabNotas("select d.Nome as Nome_disciplina, Notas as Notas from alunos a, participa_de p, disciplinas d where a.Matricula=p.Matricula and p.Cod_disc=d.Cod_disc and a.Matricula= '"+  jLabel17.getText() +"' ;");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
try {
            conecta.executaSQL("select * from  disciplinas d,professores p,Turmas t where p.Mat_Siape = t.Mat_Siape and t.Cod_disc=d.Cod_disc");
            conecta.rs.first();
            campo_codTurma.setText(String.valueOf(conecta.rs.getInt("t.Cod_turma")));
            campo_CodDisc.setText(String.valueOf(conecta.rs.getInt("d.Cod_disc")));;
            jTextField3.setText(conecta.rs.getString("d.Nome"));
            jTextField5.setText(conecta.rs.getString("d.Carga_horária"));
            jTextField4.setText(conecta.rs.getString("p.Nome"));
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Erro ao mostrar dados!\nERRO:"+ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
       try {
            conecta.executaSQL("select * from  disciplinas d,professores p,Turmas t where p.Mat_Siape = t.Mat_Siape and t.Cod_disc=d.Cod_disc");
            conecta.rs.last();
            campo_codTurma.setText(String.valueOf(conecta.rs.getInt("t.Cod_turma")));
            campo_CodDisc.setText(String.valueOf(conecta.rs.getInt("d.Cod_disc")));;
            jTextField3.setText(conecta.rs.getString("d.Nome"));
            jTextField5.setText(conecta.rs.getString("d.Carga_horária"));
            jTextField4.setText(conecta.rs.getString("p.Nome"));
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Erro ao mostrar dados!\nERRO:"+ex);
        } 
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        try {
            conecta.rs.next();
            campo_codTurma.setText(String.valueOf(conecta.rs.getInt("t.Cod_turma")));
            campo_CodDisc.setText(String.valueOf(conecta.rs.getInt("d.Cod_disc")));;
            jTextField3.setText(conecta.rs.getString("d.Nome"));
            jTextField5.setText(conecta.rs.getString("d.Carga_horária"));
            jTextField4.setText(conecta.rs.getString("p.Nome"));
            
        }catch(SQLException ex){
            Toolkit.getDefaultToolkit().beep();
        } 
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
       try { 
            conecta.rs.previous();
            campo_codTurma.setText(String.valueOf(conecta.rs.getInt("t.Cod_turma")));
            campo_CodDisc.setText(String.valueOf(conecta.rs.getInt("d.Cod_disc")));;
            jTextField3.setText(conecta.rs.getString("d.Nome"));
            jTextField5.setText(conecta.rs.getString("d.Carga_horária"));
            jTextField4.setText(conecta.rs.getString("p.Nome"));
            
        }catch(SQLException ex){
            Toolkit.getDefaultToolkit().beep();
        } 
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TelaAluno fr = new TelaAluno();
        fr.setLocationRelativeTo(null);
        fr.setDefaultCloseOperation(fr.DISPOSE_ON_CLOSE);
        fr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
public void preencherTabDiscRestantes(String SQL){
      
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"Cod Turma","Cod Disciplina","Nome da Disciplina","Professor","C.H.","Local","Horário"};
    
    conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
             do{ 
                 dados.add(new Object[]{conecta.rs.getInt("t.Cod_turma"),conecta.rs.getInt("d.Cod_disc"),conecta.rs.getString("d.Nome"),conecta.rs.getString("p.Nome"),conecta.rs.getString("d.Carga_horária"),conecta.rs.getString("t.local"),conecta.rs.getTime("t.Horário")});
    }while(conecta.rs.next());
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"Erro ao preencher a tabela \n erro:"+ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        TabDisciplinasRestantes.setModel(modelo);
        TabDisciplinasRestantes.getColumnModel().getColumn(0).setPreferredWidth(50);//indice 0 Cursos
        TabDisciplinasRestantes.getColumnModel().getColumn(0).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasRestantes.getColumnModel().getColumn(1).setPreferredWidth(50);//indice 0 Cursos
        TabDisciplinasRestantes.getColumnModel().getColumn(1).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasRestantes.getColumnModel().getColumn(2).setPreferredWidth(200);//indice 0 Cursos
        TabDisciplinasRestantes.getColumnModel().getColumn(2).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasRestantes.getColumnModel().getColumn(3).setPreferredWidth(200);//indice 0 Cursos
        TabDisciplinasRestantes.getColumnModel().getColumn(3).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasRestantes.getColumnModel().getColumn(4).setPreferredWidth(30);//indice 0 Cursos
        TabDisciplinasRestantes.getColumnModel().getColumn(4).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasRestantes.getColumnModel().getColumn(5).setPreferredWidth(70);//indice 0 Cursos
        TabDisciplinasRestantes.getColumnModel().getColumn(5).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasRestantes.getColumnModel().getColumn(6).setPreferredWidth(60);//indice 0 Cursos
        TabDisciplinasRestantes.getColumnModel().getColumn(6).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasRestantes.getTableHeader().setReorderingAllowed(false);//reorganizar a alocaçao
        TabDisciplinasRestantes.setAutoResizeMode(TabDisciplinasRestantes.AUTO_RESIZE_OFF);//nao podera ser redimensionada;
        TabDisciplinasRestantes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
}
    
    public void preencherTabDiscAlunos(String SQL){
      
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"Cod Turma","Cod Disciplina","Nome da Disciplina","Professor","C.H.","Local","Horário"};
    
    conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
             do{ 
                 dados.add(new Object[]{conecta.rs.getInt("t.Cod_turma"),conecta.rs.getInt("d.Cod_disc"),conecta.rs.getString("d.Nome"),conecta.rs.getString("r.Nome"),conecta.rs.getString("d.Carga_horária"),conecta.rs.getString("t.local"),conecta.rs.getTime("t.Horário")});
    }while(conecta.rs.next());
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"Erro ao preencher a tabela \n erro:"+ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        TabDisciplinasAluno.setModel(modelo);
        TabDisciplinasAluno.getColumnModel().getColumn(0).setPreferredWidth(50);//indice 0 Cursos
        TabDisciplinasAluno.getColumnModel().getColumn(0).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasAluno.getColumnModel().getColumn(1).setPreferredWidth(50);//indice 0 Cursos
        TabDisciplinasAluno.getColumnModel().getColumn(1).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasAluno.getColumnModel().getColumn(2).setPreferredWidth(200);//indice 0 Cursos
        TabDisciplinasAluno.getColumnModel().getColumn(2).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasAluno.getColumnModel().getColumn(3).setPreferredWidth(200);//indice 0 Cursos
        TabDisciplinasAluno.getColumnModel().getColumn(3).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasAluno.getColumnModel().getColumn(4).setPreferredWidth(30);//indice 0 Cursos
        TabDisciplinasAluno.getColumnModel().getColumn(4).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasAluno.getColumnModel().getColumn(5).setPreferredWidth(70);//indice 0 Cursos
        TabDisciplinasAluno.getColumnModel().getColumn(5).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasAluno.getColumnModel().getColumn(6).setPreferredWidth(60);//indice 0 Cursos
        TabDisciplinasAluno.getColumnModel().getColumn(6).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDisciplinasAluno.getTableHeader().setReorderingAllowed(false);//reorganizar a alocaçao
        TabDisciplinasAluno.setAutoResizeMode(TabDisciplinasAluno.AUTO_RESIZE_OFF);//nao podera ser redimensionada;
        TabDisciplinasAluno.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
}
public void preencherTabNotas(String SQL){
      
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"Nome da Disciplina","Nota"};
    
    conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
             do{ 
                 dados.add(new Object[]{conecta.rs.getString("Nome_disciplina"),conecta.rs.getFloat("Notas") });
    }while(conecta.rs.next());
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"Erro ao preencher a tabela \n erro:"+ex);
        }

ModeloTabela modelo = new ModeloTabela(dados, Colunas);
tabNotas.setModel(modelo);
tabNotas.getColumnModel().getColumn(0).setPreferredWidth(300);//indice 0 Cursos
tabNotas.getColumnModel().getColumn(0).setResizable(false);//nao pode alterar o tamanho com o mouse
tabNotas.getColumnModel().getColumn(1).setPreferredWidth(60);//indice 0 Cursos
tabNotas.getColumnModel().getColumn(1).setResizable(false);//nao pode alterar o tamanho com o mouse
tabNotas.getTableHeader().setReorderingAllowed(false);//reorganizar a alocaçao
tabNotas.setAutoResizeMode(tabNotas.AUTO_RESIZE_OFF);//nao podera ser redimensionada;
tabNotas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

 
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlunoEntrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlunoEntrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlunoEntrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlunoEntrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlunoEntrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabDisciplinasAluno;
    private javax.swing.JTable TabDisciplinasRestantes;
    private javax.swing.JTextField campo_CodDisc;
    private javax.swing.JTextField campo_codTurma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tabNotas;
    // End of variables declaration//GEN-END:variables
 
}
