/*
 * Tela do Ambiente de Professores
 */

package FramesProfessor;

import BancoDeDados.ConectaBD;
import FramesAdministrador.ModeloTabela;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author  Raphael e Leonardo
 */
public class ProfessorEntrar extends javax.swing.JFrame {
     ConectaBD conecta= new ConectaBD();//instancia da classe de conexão
     
    public void recebendo(String recebe){//Função que recebe a matricula Siape digitada na outra tela
      jLabel20.setText(recebe);
 }

    /**
     * Creates new form ProfessorEntrar
     */
    public ProfessorEntrar() {
        initComponents();
        conecta.conexao();//Chamada do metodo de conexão
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4_nomeprof = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6_regime = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10_curso = new javax.swing.JLabel();
        jLabel_matsiape = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabDiscProf = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabAlunosNaTurma = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel18_codDisc = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Bem Vindo(a)!");

        jLabel3.setText("NOME:");

        jLabel4_nomeprof.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4_nomeprof.setForeground(new java.awt.Color(0, 0, 102));

        jLabel5.setText("REGIME:");

        jLabel6_regime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6_regime.setForeground(new java.awt.Color(0, 0, 102));

        jLabel9.setText("CURSO:");

        jLabel1.setText("MATRÍCULA SIAPE:");

        jLabel10_curso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10_curso.setForeground(new java.awt.Color(0, 0, 102));

        jLabel_matsiape.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_matsiape.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5))
                                    .addGap(70, 70, 70))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(73, 73, 73)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_matsiape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4_nomeprof, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                            .addComponent(jLabel6_regime, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel11)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_matsiape, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4_nomeprof, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6_regime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(253, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados do Professor", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setText("Você ministra aula nas Turmas:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Turmas");

        TabDiscProf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TabDiscProf);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("Lançamento de Notas de Alunos");

        jLabel2.setText("Digite o Código da turma:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SELECIONAR TURMA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TabAlunosNaTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TabAlunosNaTurma);

        jLabel4.setText("Digite a Matrícula do Aluno:");

        jButton3.setBackground(new java.awt.Color(0, 51, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SALVAR NOTA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Digite a Nota do Aluno:");

        jTextField3.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField3InputMethodTextChanged(evt);
            }
        });

        jLabel10.setText("Código da Disciplina:");

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Ex: 8.5 ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(jLabel18_codDisc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(90, 90, 90)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jButton3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18_codDisc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Turmas", jPanel2);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 0));

        jLabel21.setText("Matricula SIAPE:");

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CONFIRMAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SAIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("VOLTAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton2)
                .addGap(33, 33, 33)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4))
                    .addComponent(jButton2)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         preencherTabDiscProfessores("select * from professores p, turmas t, disciplinas d \n" +
                            "where p.Mat_Siape=t.Mat_Siape and t.Cod_disc=d.Cod_disc and\n" +
                            "p.Mat_Siape='"+  jLabel20.getText() +"' order by t.Cod_turma ;");
        try {
            conecta.executaSQL("select * from professores p, curso c where p.Cod_Curso=c.Cod_Curso and p.Mat_Siape= '"+jLabel20.getText()+"' ;");
            conecta.rs.first();
           jLabel_matsiape.setText(String.valueOf(conecta.rs.getInt("p.Mat_Siape")));
           jLabel4_nomeprof.setText(conecta.rs.getString("p.Nome"));
           jLabel6_regime.setText(conecta.rs.getString("p.Regime_trabalho"));
           jLabel10_curso.setText(conecta.rs.getString("c.Nome_Curso")); 
        }catch(SQLException ex){   
            JOptionPane.showMessageDialog(null,"Erro ao mostrar dados!\nERRO:"+ex);  
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  
       if (Float.parseFloat(jTextField3.getText())>=0 && Float.parseFloat(jTextField3.getText())<=10){//Aceita apenas notas entre 0 e 10
        try{//BOTÃO DE INSERÇÃO
            PreparedStatement pst = conecta.conn.prepareStatement("UPDATE Participa_de SET Notas= ? WHERE Matricula = ? and Cod_turma=? and Cod_disc=? ;");//passagem do SQL para inserção
            pst.setString(2,jTextField2.getText());//matricula
            pst.setString(3,jTextField1.getText());//codTurma
            pst.setString(4,jLabel18_codDisc.getText());//codDisc
            pst.setString(1,jTextField3.getText());//Notas
            pst.executeUpdate();//executa a inserção
            JOptionPane.showMessageDialog(rootPane,"Salvo com Sucesso!");
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Erro ao Salvar! \n ERRO: "+ex);
        }
        
       }else
           JOptionPane.showMessageDialog(rootPane," A Nota deve estar entre 0 e 10!");
       
       preencherTabAlunosNaTurma("select * from turmas t, disciplinas d, participa_de pd, alunos a \n" +
            "where t.Cod_disc=d.Cod_disc and pd.Cod_Turma=t.Cod_Turma and pd.Cod_disc=d.Cod_disc and\n" +
            "a.matricula=pd.matricula and\n" +
            "t.Cod_turma='"+jTextField1.getText()+"' ;");//Chamada para preenchimento da tabela de alunos nas turmas 
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            conecta.executaSQL("select * from turmas t, disciplinas d, participa_de pd, alunos a \n" +
                "where t.Cod_disc=d.Cod_disc and pd.Cod_Turma=t.Cod_Turma and pd.Cod_disc=d.Cod_disc and\n" +
                "a.matricula=pd.matricula and\n" +
                "t.Cod_turma='"+jTextField1.getText()+"' ;");
            conecta.rs.first();
            jLabel18_codDisc.setText(String.valueOf(conecta.rs.getInt("d.Cod_disc")));
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"A TURMA não tem Alunos!\nERRO:"+ex);
        }
        // jLabel18_codDisc.getText();
        preencherTabAlunosNaTurma("select * from turmas t, disciplinas d, participa_de pd, alunos a \n" +
            "where t.Cod_disc=d.Cod_disc and pd.Cod_Turma=t.Cod_Turma and pd.Cod_disc=d.Cod_disc and\n" +
            "a.matricula=pd.matricula and\n" +
            "t.Cod_turma='"+jTextField1.getText()+"' ;");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        telaProfessor fr = new telaProfessor();
        fr.setLocationRelativeTo(null);
        fr.setDefaultCloseOperation(fr.DISPOSE_ON_CLOSE);
        fr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField3InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField3InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3InputMethodTextChanged
public void preencherTabDiscProfessores(String SQL){
      
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"Cod Turma","Nome da Disciplina","Semestre","Nº de Alunos","C.H.","Local","Horário"};
    
    conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
             do{ 
                 dados.add(new Object[]{conecta.rs.getInt("t.Cod_turma"),conecta.rs.getString("d.Nome"),conecta.rs.getString("t.Semestre"),conecta.rs.getString("t.Num_alunos"),conecta.rs.getString("d.Carga_horária"),conecta.rs.getString("t.local"),conecta.rs.getTime("t.Horário")});
    }while(conecta.rs.next());
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"Erro ao preencher a tabela \n erro:"+ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        TabDiscProf.setModel(modelo);
        TabDiscProf.getColumnModel().getColumn(0).setPreferredWidth(70);//indice 0 Cursos
        TabDiscProf.getColumnModel().getColumn(0).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDiscProf.getColumnModel().getColumn(1).setPreferredWidth(200);//indice 0 Cursos
        TabDiscProf.getColumnModel().getColumn(1).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDiscProf.getColumnModel().getColumn(2).setPreferredWidth(60);//indice 0 Cursos
        TabDiscProf.getColumnModel().getColumn(2).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDiscProf.getColumnModel().getColumn(3).setPreferredWidth(80);//indice 0 Cursos
        TabDiscProf.getColumnModel().getColumn(3).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDiscProf.getColumnModel().getColumn(4).setPreferredWidth(50);//indice 0 Cursos
        TabDiscProf.getColumnModel().getColumn(4).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDiscProf.getColumnModel().getColumn(5).setPreferredWidth(70);//indice 0 Cursos
        TabDiscProf.getColumnModel().getColumn(5).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDiscProf.getColumnModel().getColumn(6).setPreferredWidth(60);//indice 0 Cursos
        TabDiscProf.getColumnModel().getColumn(6).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabDiscProf.getTableHeader().setReorderingAllowed(false);//reorganizar a alocaçao
        TabDiscProf.setAutoResizeMode(TabDiscProf.AUTO_RESIZE_OFF);//nao podera ser redimensionada;
        TabDiscProf.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
}
public void preencherTabAlunosNaTurma(String SQL){
      
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"Cod Turma","Cod Disciplina","Nome Aluno","Matr. Aluno","NOTA"};
    
    conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
             do{ 
                 dados.add(new Object[]{conecta.rs.getInt("t.Cod_turma"),conecta.rs.getInt("d.Cod_disc"),conecta.rs.getString("a.Nome"),conecta.rs.getInt("a.Matricula"),conecta.rs.getString("pd.notas")});
    }while(conecta.rs.next());
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"Erro ao preencher a tabela \n erro:"+ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        TabAlunosNaTurma.setModel(modelo);
        TabAlunosNaTurma.getColumnModel().getColumn(0).setPreferredWidth(80);//indice 0 Cursos
        TabAlunosNaTurma.getColumnModel().getColumn(0).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabAlunosNaTurma.getColumnModel().getColumn(1).setPreferredWidth(80);//indice 0 Cursos
        TabAlunosNaTurma.getColumnModel().getColumn(1).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabAlunosNaTurma.getColumnModel().getColumn(2).setPreferredWidth(200);//indice 0 Cursos
        TabAlunosNaTurma.getColumnModel().getColumn(2).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabAlunosNaTurma.getColumnModel().getColumn(3).setPreferredWidth(80);//indice 0 Cursos
        TabAlunosNaTurma.getColumnModel().getColumn(3).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabAlunosNaTurma.getColumnModel().getColumn(4).setPreferredWidth(80);//indice 0 Cursos
        TabAlunosNaTurma.getColumnModel().getColumn(4).setResizable(false);//nao pode alterar o tamanho com o mouse
        TabAlunosNaTurma.getTableHeader().setReorderingAllowed(false);//reorganizar a alocaçao
        TabAlunosNaTurma.setAutoResizeMode(TabAlunosNaTurma.AUTO_RESIZE_OFF);//nao podera ser redimensionada;
        TabAlunosNaTurma.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorEntrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorEntrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorEntrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorEntrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorEntrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabAlunosNaTurma;
    private javax.swing.JTable TabDiscProf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel10_curso;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18_codDisc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4_nomeprof;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6_regime;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_matsiape;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
